In [2]:
import yfinance as yf
dat = yf.Ticker("MSFT")

In [3]:
dat

yfinance.Ticker object <MSFT>

In [4]:
dat.history(period="1y", interval="1d", auto_adjust=True, actions=True)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-06-26 00:00:00-04:00,445.583705,450.148711,444.779871,448.719666,16507000,0.0,0.0
2024-06-27 00:00:00-04:00,448.739534,452.699196,448.332650,449.404449,14806300,0.0,0.0
2024-06-28 00:00:00-04:00,449.622777,451.915199,443.013447,443.549347,28362300,0.0,0.0
2024-07-01 00:00:00-04:00,445.246308,453.890028,442.269134,453.254913,17662800,0.0,0.0
2024-07-02 00:00:00-04:00,449.751766,456.093131,449.662424,455.785492,13979800,0.0,0.0
...,...,...,...,...,...,...,...
2025-06-18 00:00:00-04:00,478.000000,481.000000,474.459991,480.239990,17526500,0.0,0.0
2025-06-20 00:00:00-04:00,482.230011,483.459991,476.869995,477.399994,37576200,0.0,0.0
2025-06-23 00:00:00-04:00,478.209991,487.750000,472.510010,486.000000,24864000,0.0,0.0
2025-06-24 00:00:00-04:00,488.950012,491.850006,486.799988,490.109985,22305600,0.0,0.0
2025-06-25 00:00:00-04:00,492.040009,494.559998,489.390015,492.269989,17475600,0.0,0.0

In [ ]:
tickers = yf.Tickers('MSFT AAPL GOOG')

tickers.tickers['MSFT'].info

yf.download(['MSFT', 'AAPL', 'GOOG'], period='1mo')

C:\Users\qnhl\AppData\Local\Temp\ipykernel_35196\2129763561.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  yf.download(['MSFT', 'AAPL', 'GOOG'], period='1mo')
[*********************100%***********************]  3 of 3 completed

Price            Close                                High              \
Ticker            AAPL        GOOG        MSFT        AAPL        GOOG
Date
2025-05-27  200.210007  173.771118  460.690002  200.740005  174.080744
2025-05-28  200.419998  173.171860  457.359985  202.729996  176.268129
2025-05-29  199.949997  172.752365  458.679993  203.809998  175.189423
2025-05-30  200.850006  172.642487  460.359985  201.960007  173.231775
2025-06-02  201.699997  170.165451  461.970001  202.130005  170.856622
2025-06-03  203.270004  167.508667  462.970001  203.770004  169.596154
2025-06-04  202.820007  169.186630  463.869995  206.240005  169.376405
2025-06-05  200.630005  169.606125  467.679993  204.750000  172.153066
2025-06-06  203.919998  174.709991  470.380005  205.699997  175.618903
2025-06-09  201.449997  177.630005  472.750000  206.000000  177.914993
2025-06-10  202.669998  180.009995  470.920013  204.350006  182.445007
2025-06-11  198.779999  178.789993  472.619995  204.500000  181.750000
2025-06-12  199.199997  176.970001  478.869995  199.679993  178.130005
2025-06-13  196.449997  175.880005  474.959991  200.369995  178.343002
2025-06-16  198.419998  177.940002  479.140015  198.690002  178.244995
2025-06-17  195.639999  177.229996  478.040009  198.389999  178.714996
2025-06-18  196.580002  173.979996  480.239990  197.570007  177.824005
2025-06-20  201.000000  167.729996  477.399994  201.699997  175.365005
2025-06-23  201.500000  166.009995  486.000000  202.300003  168.479996
2025-06-24  200.300003  167.740005  490.109985  203.440002  169.250000
2025-06-25  201.559998  171.490005  492.269989  203.669998  173.360001

Price                          Low                                Open  \
Ticker            MSFT        AAPL        GOOG        MSFT        AAPL
Date
2025-05-27  460.950012  197.429993  171.004455  456.119995  198.300003
2025-05-28  462.519989  199.899994  172.807292  456.929993  200.589996
2025-05-29  461.720001  198.509995  171.573774  455.309998  203.580002
2025-05-30  461.679993  196.779999  168.322667  455.540009  199.369995
2025-06-02  462.109985  200.119995  168.447515  456.890015  200.279999
2025-06-03  464.140015  200.960007  166.479890  460.859985  201.350006
2025-06-04  465.690002  202.100006  167.593544  463.019989  202.910004
2025-06-05  469.649994  200.149994  169.146686  464.029999  203.500000
2025-06-06  473.339996  202.050003  172.093142  468.779999  203.000000
2025-06-09  473.429993  200.020004  175.660004  468.619995  204.389999
2025-06-10  472.799988  200.570007  176.475006  466.959991  200.600006
2025-06-11  475.470001  198.410004  178.000000  469.660004  203.500000
2025-06-12  480.420013  197.360001  176.110001  473.519989  199.080002
2025-06-13  479.179993  195.699997  173.570007  472.760010  199.729996
2025-06-16  480.690002  196.559998  175.820007  475.000000  197.300003
2025-06-17  478.739990  195.210007  175.940002  474.079987  197.199997
2025-06-18  481.000000  195.070007  172.839996  474.459991  195.940002
2025-06-20  483.459991  196.860001  166.270004  476.869995  198.240005
2025-06-23  487.750000  198.960007  163.330002  472.510010  201.630005
2025-06-24  491.850006  200.199997  166.910004  486.799988  202.589996
2025-06-25  494.559998  200.619995  168.561005  489.390015  201.449997

Price                                 Volume
Ticker            GOOG        MSFT      AAPL      GOOG      MSFT
Date
2025-05-27  171.094343  456.480011  56288500  24341300  20974300
2025-05-28  173.771130  461.220001  45339700  25999200  17086300
2025-05-29  174.789909  461.549988  51396800  21233600  13974800
2025-05-30  172.203012  459.720001  70819900  36258300  34770500
2025-06-02  168.807083  457.140015  35423300  24742900  16626500
2025-06-03  168.662279  461.470001  46381600  25386700  15743800
2025-06-04  168.077962  464.000000  43604000  18508700  14162700
2025-06-05  171.413949  464.959991  55126100  25375400  20131700
2025-06-06  172.093142  470.089996  46607700  22258100  15285600
2025-06-09  175.869995  469.700012  72862600  18817600  16469900
2025-06-10  177.759995  471.190002  54672600  32908000  15375900
2025-06-11  181.229996  470.019989  60989900  18994400  16399200
2025-06-12  177.479996  475.019989  43904600  17345900  18950600
2025-06-13  173.580002  476.410004  51447300  20873200  16814500
2025-06-16  175.904999  475.209991  43020700  18132500  15626100
2025-06-17  177.000000  475.399994  38856200  17656100  15414100
2025-06-18  177.279999  478.000000  45394700  32531800  17526500
2025-06-20  174.865005  482.230011  96813500  55402600  37576200
2025-06-23  167.320007  478.209991  55814300  36975600  24864000
2025-06-24  167.684998  488.950012  54064000  27310300  22305600
2025-06-25  168.649994  492.040009  39454000  23593500  17475600